-- Run this in your Supabase SQL Editor to create the table

create table cims_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_name text,
  enrollment_number text,
  choices jsonb,
  grade text,
  score numeric,
  pnl numeric,
  warnings text[],
  errors text[],
  submitted_at timestamp with time zone
);

-- Enable Row Level Security (RLS) if you want to restrict access, 
-- but for this student project, you might want to allow anon inserts:
alter table cims_submissions enable row level security;

create policy "Enable insert for everyone" 
on cims_submissions for insert 
with check (true);

create policy "Enable select for everyone" 
on cims_submissions for select 
using (true);
